### ISSUE TITLE
TopasLocation not working for OpenTOPAS

### ISSUE THREAD

**Issue by dixinchen** [Image-X-Institute/TopasOpt#133]
Hi! I'm working through a worked example with OpenTOPAS but encountered an issue running `RunOptimisation_main.py`. The error suggests that the TOPAS binary can't be found at the specified location. I followed the installation instructions for OpenTOPAS, and my topas binary is located at `/Applications/TOPAS/OpenTOPAS-install/bin/topas`, which is the same as in the instructions and is what's being set in the script. Do I need to make any changes to the TopasLocation to make it point to the OpenTOPAS installation location?

**Comment by bwheelz36** [comment]
Hey, thanks for reporting. Would you mind posting the exact script you are using so I can investigate?

**Comment by brendan-whelan-seetreat** [comment]
Not sure if you've already update the `TopasLocation` variable but this is described here:
https://image-x-institute.github.io/TopasOpt/code_docs.html#TopasOpt.Optimisers.TopasOptBaseClass

**Comment by dixinchen** [comment]
I updated the `TopasLocation` to `/Applications/TOPAS/OpenTOPAS-install` and `G4dataLocation` to `/Applications/GEANT4/G4DATA` and it works now. Thank you!
